//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svyaznoy_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdSotrudnik { get; set; }
        public string TypeConsult { get; set; }
        public string MobileConsult { get; set; }
        public string AcsessConsult { get; set; }
        public string OperConsult { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual SotrudnikSet SotrudnikSet { get; set; }
    }
}
