//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svyaznoy_project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Svyaznoy_projectEntities2 : DbContext
    {
        public Svyaznoy_projectEntities2()
            : base("name=Svyaznoy_projectEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ClientSet> ClientSet { get; set; }
        public virtual DbSet<ConsultSet> ConsultSet { get; set; }
        public virtual DbSet<SellsSet> SellsSet { get; set; }
        public virtual DbSet<SotrudnikSet> SotrudnikSet { get; set; }
    }
}
