//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Svyaznoy_project
{
    using System;
    using System.Collections.Generic;
    
    public partial class SellsSet
    {
        public int Id { get; set; }
        public int IdClient { get; set; }
        public int IdSotrudnik { get; set; }
        public int TypeTovar { get; set; }
        public string ModelMobile { get; set; }
        public string NameAcsess { get; set; }
        public string NameOper { get; set; }
        public int Price { get; set; }
        public Nullable<int> Garant { get; set; }
    
        public virtual ClientSet ClientSet { get; set; }
        public virtual SotrudnikSet SotrudnikSet { get; set; }
    }
}
